### ISSUE TITLE
does not run in Docker container

### ISSUE THREAD

**Issue by rozek** [AllanCerveaux/svg_repo_dl#5]
I'm currently trying to run the downloader from within a docker container based on the official python:3-alim image

At first, it complained about a missing module `requests`

After `pip install requests` it now stops with

```
INFO: 📣 Download will start for dazzle-line-icons pack !
Traceback (most recent call last):
  File "/usr/local/bin/svgrepodl", line 33, in <module>
    sys.exit(load_entry_point('svgrepodl', 'console_scripts', 'svgrepodl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/svg_repo_dl/svgrepodl/__main__.py", line 6, in main
    cli()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/svg_repo_dl/svgrepodl/commands.py", line 38, in cli
    downloader(url, dest)
  File "/work/svg_repo_dl/svgrepodl/utils.py", line 10, in downloader
    driver = browserConfiguration(path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/svg_repo_dl/svgrepodl/utils.py", line 30, in browserConfiguration
    return webdriver.Firefox(firefox_profile=profile, options=options, service_log_path=os.path.devnull)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'
```

**Comment by rozek** [comment]
After many other changes (e.g., the script needs Firefox and a configuration which allows it to run in headless mode) I finally succeeded in connecting to svgrepo.com.

However, there, it did not find any link to download...(sigh)

**Comment by rozek** [comment]
ah, I also had to change the CSS selector used to locate the various icons: it should now be

`.style_Node__7ZTBP a`

**Comment by rozek** [comment]
well,

it actually took much longer than expected to get the tool running: I had to make so many changes (including a switch to `wget` for the actual download rather than using a headless Firefox for that purpose) that I made these changes in [my own fork of this repo](https://github.com/rozek/svg_repo_dl)

But now, the icons are downloading!

**Comment by AllanCerveaux** [comment]
Thanks for your interest in this old project, which met one of my needs a long time ago.
It's cool that you took the time to adapt it to your needs.

If you want, you can make a PR to contribute, that would help a lot of other people who want to use this tool or if you allow me I can add my own solution.

**Comment by rozek** [comment]
I would be honored to provide a pull request.

However, since I'm not a regular Python programmer, I can only claim that my code "works on my machine".

Thus, it would be nice if you could test my changes on your machine as well - everything has been prepared to be used out-of-the-box (the code currently even refers to my fork rather than your repo)

If everything works fine, I'll change all references back to your repo again and prepare the actual pull request.

**Comment by drzraf** [comment]
Can likely be closed, now
